### ISSUE TITLE
libudev support for nvme

### ISSUE THREAD

**Issue by sammj** [open-power/buildroot#19]
Future op-build releases will presumably choose to install the nvme package to support NVMe devices, however the current buildroot nvme.mk file unconditionally disables libudev support which is required by commands like `nvme list`.

I've submitted a patch to buildroot upstream to make libudev support configurable, which is being tracked here: http://patchwork.ozlabs.org/patch/611565/

**Comment by sammj** [comment]
And since the buildroot guys are superhumanly responsive an updated version (http://patchwork.ozlabs.org/patch/611957/) is now merged as https://github.com/buildroot/buildroot/commit/c0293c3cc9f99b81c78ed193a7ce6187c6c4c78d

@shenki We'll want to get that fix once it's in a tagged release.

**Comment by shenki** [comment]
Added to our buildroot tree as https://github.com/open-power/buildroot/commit/91bcf5612f9c2f1b3d6514a3b056a6cef307b5e1. Will close when this hits op-build

**Comment by sammj** [comment]
This is now in (at least) 2016.05-op-build, closing.
