### ISSUE TITLE
Feature Request: Relocate Toolchain (SDK) in later versions of buildroot.

### ISSUE THREAD

**Issue by scprek** [open-power/buildroot#21]
Hi,

The OpenPOWER team is working on improving Jenkins CI time and have been doing external toolchain work. We currently have a jenkins job that builds the toolchains per OS, but they cannot be relocated. We can set BR2_HOST_DIR to the directory of our choosing and will work on that for now.

However discussions on the buildroot mailing list suggested that relocation work has been enabled in more recent versions of buildroot.

For example read about this:
Patches
http://lists.busybox.net/pipermail/buildroot/2015-July/132483.html
and found this
https://github.com/buildroot/buildroot/blob/master/support/scripts/fix-rpath

Not sure of all the dependencies to get this to work and if there is a subset of patches we could just toss on that could work too.

If there's another medium that should be used to discuss this, let me know.

Thanks,

**Comment by scprek** [comment]
It may be as simple as downloading that fix-rpath script and calling it?

**Comment by shenki** [comment]
@scprek We updated to Buildroot 2017.08 as of today. Does this have the required support?

**Comment by sambltc** [comment]
You might want to have a look at this more recent post from the mailing list:

http://lists.busybox.net/pipermail/buildroot/2017-July/196670.html

It looks like it's now as simple as "make sdk".

**Comment by scprek** [comment]
What timing, I had no idea an update was coming in essentially the same day.
I will try out the "make sdk", but looks like the rest of the relocate content is now in our fork anyhow

Thanks.

**Comment by scprek** [comment]
make sdk did a full openpower compile for me. We just want the external toolchain to be compiled so we can use EXTERNAL_TOOLCHAIN.
