### ISSUE TITLE
Support for booting compressed kernels

### ISSUE THREAD

**Issue by GHF** [open-power/buildroot#5]
Please merge support from Cédric Le Goater <clg@fr.ibm.com> for kexec'ing compressed kernel images: legoater/kexec-lite@c0f9cc722eb05709f452b1a07f46b421b834e1e7

**Comment by jk-ozlabs** [comment]
Whoa, hadn't seen this one.

@oohal is implementing compression support in the zImage wrapper, so no changes to kexec are needed here. Closing the buildroot issue.
